# netlify.toml

[build]
  command = "pnpm run build:client"
  publish = "dist"
  # Astro outputs to "dist" by default

# Optional: specify Node version if needed
[build.environment]
  NODE_VERSION = "22.0.0"

[functions]
  directory = "netlify/functions"

# If you’re using Astro’s Node adapter, ensure the SSR function is deployed
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

# Optional: security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Dev section (used only locally with Netlify CLI)
[dev]
  command = "pnpm run dev"
  port = 3000
  targetPort = 4321
